env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

env = QT_AUTO_SCREEN_SCALE_FACTOR, 1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = QT_QPA_PLATFORMTHEME, qt5ct

env = QT_QPA_PLATFORM, wayland;xcb
env = CLUTTER_BACKEND, wayland
env = GDK_BACKEND, wayland,x11
env = SDL_VIDEODRIVER, wayland

env = GTK_THEME, Arc-Dark-solid

env = PATH, /home/r3dkar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
